// Central env-var schema. Every documented knob in .env.example is declared
// here so boot can fail fast on malformed or missing required values instead
// of silently falling back. See envLoader.js for parsing semantics and
// test/envDocumentation.test.js for the .env.example sync contract.
export const ENV_SCHEMA = {
  // --- Core ---
  UPBIT_ACCESS_KEY: { type: 'string', secret: true },
  UPBIT_SECRET_KEY: { type: 'string', secret: true },
  UPBIT_REQUEST_TIMEOUT_MS: { type: 'int', min: 0 },
  UPBIT_MIN_REQUEST_INTERVAL_MS: { type: 'int', min: 0 },
  // --- TRADING MODE ---
  DRY_RUN: { type: 'bool' },
  TRADING_STRATEGY: { type: 'string' },
  SCALP_CANDLE_UNIT: { type: 'int' },
  SCALP_RSI_PERIOD: { type: 'int', min: 0 },
  SCALP_RSI_OVERSOLD: { type: 'int' },
  SCALP_RSI_OVERBOUGHT: { type: 'int' },
  SCALP_OVERSOLD_LOOKBACK: { type: 'int', min: 0 },
  SCALP_CANDLE_COUNT: { type: 'int', min: 0 },
  SCALP_MAX_CANDLE_AGE_SECONDS: { type: 'number', min: 0 },
  SCALP_MIN_REBOUND_PERCENT: { type: 'number' },
  SCALP_MAX_REBOUND_PERCENT: { type: 'number' },
  SCALP_MIN_RSI_RECOVERY: { type: 'number' },
  SCALP_MIN_VOLUME_RATIO: { type: 'number' },
  SCALP_VOLUME_LOOKBACK: { type: 'int', min: 0 },
  SCALP_MIN_CLOSE_STRENGTH: { type: 'number' },
  SCALP_TREND_PERIOD: { type: 'int', min: 0 },
  SCALP_TREND_SLOPE_LOOKBACK: { type: 'int', min: 0 },
  SCALP_MIN_TREND_SLOPE_PERCENT: { type: 'number' },
  SCALP_REQUIRE_PREVIOUS_HIGH_BREAK: { type: 'bool' },
  SCALP_MAX_SIGNAL_RANGE_PERCENT: { type: 'number' },
  SCALP_MIN_SIGNAL_RANGE_PERCENT: { type: 'number' },
  SCALP_MARKET_REGIME_ENABLED: { type: 'bool' },
  SCALP_MARKET_REGIME_LOOKBACK: { type: 'int', min: 0 },
  SCALP_MARKET_REGIME_MIN_BREADTH: { type: 'number', min: 0, max: 1 },
  SCALP_MARKET_REGIME_MIN_RETURN_PERCENT: { type: 'number' },
  SCALP_PORTFOLIO_REQUIRE_NEXT_CANDLE_BULLISH: { type: 'bool' },
  SCALP_REQUIRE_REBOUND_BELOW_OVERBOUGHT: { type: 'bool' },
  BB_PERIOD: { type: 'int', min: 0 },
  BB_STD_DEV: { type: 'number' },
  EMA_LONG: { type: 'int' },
  SCALP_SIGNAL_PROFILE: { type: 'enum', values: ['rsi_rebound', 'momentum_breakout', 'bb_reclaim', 'trend_rebound'] },
  SCALP_ENTRY_DELAY_MIN_MS: { type: 'int', min: 0 },
  SCALP_ENTRY_DELAY_MAX_MS: { type: 'int', min: 0 },
  SCALP_MAX_ENTRY_RETRACE_PERCENT: { type: 'number' },
  SCALP_MAX_ENTRY_CHASE_PERCENT: { type: 'number' },
  SCALP_BREAK_EVEN_TRIGGER_PERCENT: { type: 'number' },
  SCALP_BREAK_EVEN_OFFSET_PERCENT: { type: 'number' },
  SCALP_TRAILING_ACTIVATION_PERCENT: { type: 'number' },
  SCALP_TRAILING_STOP_PERCENT: { type: 'number' },
  SCALP_MAX_HOLD_MINUTES: { type: 'number', min: 0 },
  SCALP_MAX_LOSING_HOLD_MINUTES: { type: 'number', min: 0 },
  SCALP_WINNER_EXTEND_MINUTES: { type: 'number', min: 0 },
  SCALP_WINNER_EXTEND_MIN_PROFIT_PERCENT: { type: 'number' },
  SCALP_WINNER_SHADOW_EXTEND_MINUTES: { type: 'number', min: 0 },
  SCALP_WINNER_SHADOW_EXTEND_MIN_PROFIT_PERCENT: { type: 'number' },
  SCALP_WINNER_SHADOW_MAX_REBOUND_PERCENT: { type: 'number' },
  SCALP_MAX_ENTRIES_PER_SIGNAL_WINDOW: { type: 'int', min: 0 },
  SCALP_RISK_CHECK_INTERVAL_MS: { type: 'int', min: 0 },
  SCALP_MAX_RISK_DATA_GAP_SECONDS: { type: 'number', min: 0 },
  SCALP_MAX_ANALYSIS_DATA_GAP_SECONDS: { type: 'number', min: 0 },
  SCALP_COOLDOWN_AFTER_LOSS_MINUTES: { type: 'number', min: 0 },
  SCALP_MAX_CONSECUTIVE_LOSSES: { type: 'int', min: 0 },
  SCALP_LOSS_CIRCUIT_BREAKER_COUNT: { type: 'int', min: 0 },
  SCALP_LOSS_CIRCUIT_BREAKER_WINDOW_MINUTES: { type: 'number', min: 0 },
  SCALP_LOSS_CIRCUIT_BREAKER_COOLDOWN_MINUTES: { type: 'number', min: 0 },
  SCALP_PAPER_MIN_DAYS: { type: 'int', min: 0 },
  SCALP_PAPER_MIN_TRADES: { type: 'int', min: 0 },
  SCALP_PAPER_MIN_RETURN_PERCENT: { type: 'number' },
  SCALP_PAPER_MAX_DRAWDOWN_PERCENT: { type: 'number' },
  SCALP_PAPER_MAX_HEARTBEAT_GAP_MINUTES: { type: 'number', min: 0 },
  SCALP_PAPER_MIN_STORAGE_MIB: { type: 'number', min: 0 },
  SCALP_MAX_MARKETS: { type: 'int', min: 0 },
  SCALP_MAX_POSITIONS: { type: 'int', min: 0 },
  SCALP_PORTFOLIO_ALLOCATION: { type: 'number', min: 0, max: 1 },
  SCALP_INVESTMENT_RATIO: { type: 'number', min: 0, max: 1 },
  SCALP_STOP_LOSS_PERCENT: { type: 'number' },
  SCALP_TAKE_PROFIT_PERCENT: { type: 'number' },
  SCALP_ALLOW_AVERAGING: { type: 'bool' },
  SCALP_REQUIRE_VALIDATION_PASS: { type: 'bool' },
  PAPER_FORWARD_MODE: { type: 'bool' },
  PAPER_FORWARD_VERBOSE: { type: 'bool' },
  PAPER_SMOKE_SECONDS: { type: 'number', min: 0 },
  PAPER_SMOKE_INTERVAL_MS: { type: 'number', min: 0 },
  PAPER_SMOKE_MAX_MARKETS: { type: 'number', min: 0 },
  PAPER_SMOKE_SEED_MONEY: { type: 'number', min: 0 },
  PAPER_SMOKE_OUTPUT_DIR: { type: 'string' },
  PAPER_SMOKE_MARKETS: { type: 'list' },
  PAPER_SMOKE_FRESHNESS_LEDGER: { type: 'string' },
  PAPER_SMOKE_MIN_FRESHNESS_OBSERVATIONS: { type: 'number', min: 0 },
  PAPER_SMOKE_MAX_STALE_RATE: { type: 'number' },
  SCALP_MARKET_QUALITY_MIN_OBSERVATIONS: { type: 'number', min: 0 },
  SCALP_MARKET_QUALITY_MAX_STALE_RATE: { type: 'number' },
  PAPER_ALLOW_CONCURRENT_SESSIONS: { type: 'bool' },
  SCALP_VALIDATION_CANDLE_COUNT: { type: 'number', min: 0 },
  SCALP_VALIDATION_MARKET_COUNT: { type: 'number', min: 0 },
  SCALP_VALIDATION_MAX_CANDIDATES: { type: 'number', min: 0 },
  SCALP_VALIDATION_FIXED: { type: 'bool' },
  SCALP_VALIDATION_MIN_TRAINING_TRADES: { type: 'number', min: 0 },
  SCALP_VALIDATION_MIN_TRAINING_PROFIT_FACTOR: { type: 'number' },
  SCALP_VALIDATION_MIN_TRAINING_RETURN_PERCENT: { type: 'number' },
  SCALP_VALIDATION_REQUIRE_STATISTICAL_CONFIDENCE: { type: 'bool' },
  SCALP_VALIDATION_MIN_TRAINING_CONFIDENCE_TRADES: { type: 'number', min: 0 },
  SCALP_VALIDATION_MIN_CONFIDENCE_TRADES: { type: 'number', min: 0 },
  SCALP_VALIDATION_MIN_CONFIDENCE_LOWER_PERCENT: { type: 'number' },
  SCALP_VALIDATION_MARKETS: { type: 'list' },
  SCALP_VALIDATION_CANDLES_FILE: { type: 'string' },
  SCALP_VALIDATION_CONFIG_SNAPSHOT_FILE: { type: 'string' },
  SCALP_NO_TRADE_FILL_CANDLES_FILE: { type: 'string' },
  SCALP_NO_TRADE_FILL_MARKETS: { type: 'list' },
  SCALP_NO_TRADE_FILL_OUTPUT_FILE: { type: 'string' },
  SCALP_NO_TRADE_FILL_CACHE_OUTPUT_FILE: { type: 'string' },
  SCALP_NO_TRADE_FILL_MAX_INTERVALS: { type: 'number', min: 0 },
  SCALP_NO_TRADE_FILL_CANDLE_UNIT: { type: 'string' },
  SCALP_NO_TRADE_FILL_REQUIRE_STATISTICAL_CONFIDENCE: { type: 'bool' },
  SCALP_VALIDATION_CANDLE_UNIT: { type: 'number' },
  SCALP_VALIDATION_INITIAL_BALANCE: { type: 'number', min: 0 },
  SCALP_VALIDATION_FEE: { type: 'number' },
  SCALP_VALIDATION_SLIPPAGE: { type: 'number' },
  SCALP_VALIDATION_TRAIN_RATIO: { type: 'number', min: 0, max: 1 },
  SCALP_VALIDATION_MIN_CANDLES: { type: 'number', min: 0 },
  SCALP_VALIDATION_OUTPUT_FILE: { type: 'string' },
  SCALP_VALIDATION_MIN_TRADES: { type: 'number', min: 0 },
  SCALP_VALIDATION_MIN_RETURN_PERCENT: { type: 'number' },
  SCALP_VALIDATION_MIN_PROFIT_FACTOR: { type: 'number' },
  SCALP_VALIDATION_MAX_DRAWDOWN: { type: 'number' },
  SCALP_SEGMENT_CANDLES_FILE: { type: 'string' },
  SCALP_SEGMENT_MARKETS: { type: 'list' },
  SCALP_SEGMENT_CANDLE_UNIT: { type: 'string' },
  SCALP_SEGMENT_MAX_GAP_SECONDS: { type: 'number', min: 0 },
  SCALP_SEGMENT_MIN_CANDLES: { type: 'number', min: 0 },
  SCALP_SEGMENT_OUTPUT_FILE: { type: 'string' },
  SCALP_PORTFOLIO_VALIDATION_MARKETS: { type: 'list' },
  SCALP_PORTFOLIO_VALIDATION_MARKET_COUNT: { type: 'number', min: 0 },
  SCALP_PORTFOLIO_VALIDATION_CANDLE_COUNT: { type: 'number', min: 0 },
  SCALP_PORTFOLIO_VALIDATION_FOLDS: { type: 'number', min: 0 },
  SCALP_PORTFOLIO_VALIDATION_MIN_TRADES: { type: 'number', min: 0 },
  SCALP_PORTFOLIO_VALIDATION_TUNED: { type: 'bool' },
  SCALP_PORTFOLIO_INITIAL_TRAIN_RATIO: { type: 'number', min: 0, max: 1 },
  SCALP_PORTFOLIO_CANDLES_FILE: { type: 'string' },
  SCALP_PORTFOLIO_VALIDATION_OUTPUT_FILE: { type: 'string' },
  SCALP_VARIANT_MARKETS: { type: 'list' },
  SCALP_VARIANT_MARKET_COUNT: { type: 'number', min: 0 },
  SCALP_VARIANT_CANDLE_COUNT: { type: 'number', min: 0 },
  SCALP_VARIANT_NAMES: { type: 'list' },
  SCALP_VARIANT_CANDLES_FILE: { type: 'string' },
  SCALP_VARIANT_CANDLES_OUTPUT_FILE: { type: 'string' },
  SCALP_VARIANT_OUTPUT_FILE: { type: 'string' },
  SHADOW_VALIDATION_MARKET: { type: 'string' },
  SHADOW_VALIDATION_CANDLES_FILE: { type: 'string' },
  SHADOW_VALIDATION_OUTPUT_FILE: { type: 'string' },
  // --- TARGET COINS ---
  TARGET_COINS: { type: 'string' },
  TARGET_COIN: { type: 'string' },
  // --- PORTFOLIO SETTINGS ---
  MAX_POSITIONS: { type: 'int' },
  PORTFOLIO_ALLOCATION: { type: 'number', min: 0, max: 1 },
  INVESTMENT_RATIO: { type: 'number', min: 0, max: 1 },
  // --- DRY RUN SETTINGS ---
  DRY_RUN_SEED_MONEY: { type: 'int', min: 0 },
  CHECK_INTERVAL_DRY: { type: 'int' },
  // --- RISK MANAGEMENT ---
  STOP_LOSS_PERCENT: { type: 'number' },
  TAKE_PROFIT_PERCENT: { type: 'number' },
  // --- TECHNICAL INDICATORS ---
  RSI_PERIOD: { type: 'int', min: 0 },
  RSI_OVERSOLD: { type: 'int' },
  RSI_OVERBOUGHT: { type: 'int' },
  BUY_THRESHOLD: { type: 'int' },
  SELL_THRESHOLD: { type: 'int' },
  TECHNICAL_WEIGHT: { type: 'number', min: 0, max: 1 },
  NEWS_WEIGHT: { type: 'number', min: 0, max: 1 },
  // --- OPTIMIZATION SETTINGS ---
  OPTIMIZATION_DAYS: { type: 'int', min: 0 },
  OPTIMIZATION_INTERVAL: { type: 'int', min: 0 },
  OPTIMIZATION_INTERVAL_DRY: { type: 'int' },
  POPULATION_SIZE: { type: 'int', min: 0 },
  GENERATIONS: { type: 'int' },
  // --- BACKTESTING SETTINGS ---
  BACKTEST_INTERVAL: { type: 'int', min: 0 },
  BACKTEST_DAYS: { type: 'int', min: 0 },
  // --- SERVER SETTINGS ---
  DASHBOARD_PORT: { type: 'int', min: 0, max: 65535 },
  DASHBOARD_TOKEN: { type: 'string', secret: true },
  DASHBOARD_ALLOW_INSECURE: { type: 'bool' },
  DASHBOARD_HOST: { type: 'string' },
  DASHBOARD_CORS_ORIGINS: { type: 'string' },
  // --- AI ADVISOR / LONG-RUN MONITORING ---
  AI_ADVISOR_ENABLED: { type: 'bool' },
  AI_ADVISOR_TIMEOUT_MS: { type: 'int', min: 0 },
  AI_PROVIDER_FAILURE_COOLDOWN_MS: { type: 'int', min: 0 },
  AI_CODEX_IGNORE_USER_CONFIG: { type: 'bool' },
  AI_LOCAL_BRIEF_ENABLED: { type: 'bool' },
  AI_MONITORING_FILE: { type: 'string' },
  AI_CODEX_BIN: { type: 'string' },
  AI_CLAUDE_BIN: { type: 'string' },
  AI_GPT_MODEL: { type: 'string' },
  AI_CLAUDE_MODEL: { type: 'string' },
  AI_EVALUATION_MINUTES: { type: 'number', min: 0 },
  AI_EVALUATION_NEUTRAL_BAND_PERCENT: { type: 'number' },
  AI_EVALUATION_MIN_SAMPLES: { type: 'int', min: 0 },
  PAPER_AI_MONITORING: { type: 'bool' },
  PAPER_AI_PROVIDERS: { type: 'list' },
  PAPER_AI_EVENTS: { type: 'list' },
  PAPER_AI_AUTO_CONSULT_EVENTS: { type: 'list' },
  PAPER_AI_COINS: { type: 'list' },
  PAPER_AI_COOLDOWN_SECONDS: { type: 'number', min: 0 },
  PAPER_AI_SESSION_NAME: { type: 'string' },
  PAPER_AI_HORIZON: { type: 'string' },
  PAPER_AI_EVALUATION_NEUTRAL_BAND_PERCENT: { type: 'number' },
  PAPER_AI_EVALUATION_MIN_SAMPLES: { type: 'number', min: 0 },
  STAGING_OUTPUT_DIR: { type: 'string' },
  STAGING_PORT: { type: 'int', min: 0, max: 65535 },
  STAGING_TARGET_COINS: { type: 'list' },
  STAGING_CHECK_INTERVAL_MS: { type: 'int', min: 0 },
  AI_REPLAY_CANDLES_FILE: { type: 'string' },
  AI_REPLAY_OUTPUT_FILE: { type: 'string' },
  AI_REPLAY_PROVIDER: { type: 'string' },
  AI_REPLAY_MAX_SAMPLES: { type: 'number', min: 0 },
  AI_REPLAY_HORIZON_CANDLES: { type: 'number' },
  AI_REPLAY_MIN_SPACING_CANDLES: { type: 'number', min: 0 },
  AI_REPLAY_NEUTRAL_BAND_PERCENT: { type: 'number' },
  AI_REPLAY_CONFIRMED_ONLY: { type: 'bool' },
  AI_REPLAY_MARKETS: { type: 'list' },
  AI_ROBUSTNESS_REPORT_FILES: { type: 'list' },
  AI_ROBUSTNESS_MIN_NON_NEUTRAL: { type: 'number' },
  AI_ROBUSTNESS_SCOPE: { type: 'string' },
  AI_ROBUSTNESS_OUTPUT_FILE: { type: 'string' },
  AI_SMOKE_PROVIDERS: { type: 'list' },
  PAPER_DASHBOARD_LEDGER_FILE: { type: 'string' },
  PORTFOLIO_HISTORY_FILE: { type: 'string' },
  DRY_PORTFOLIO_FILE: { type: 'string' },
  PAPER_VALIDATION_FILE: { type: 'string' },
  NODE_TEST_CONTEXT: { type: 'string' },
  SCALP_HTF_MOMENTUM_CANDLES_FILE: { type: 'string' },
  SCALP_HTF_MOMENTUM_MARKETS: { type: 'list' },
  SCALP_HTF_MOMENTUM_OUTPUT_FILE: { type: 'string' },
  SCALP_HTF_MOMENTUM_FILL_NO_TRADE: { type: 'bool' },
  SCALP_HTF_MOMENTUM_MAX_FILL_INTERVALS: { type: 'number', min: 0 },
  SCALP_HTF_MOMENTUM_CANDLE_COUNT: { type: 'number', min: 0 },
  SCALP_HTF_BASE_CANDLE_UNIT: { type: 'number' },
  SCALP_HTF_FOLDS: { type: 'number', min: 0 },
  SCALP_HTF_MIN_TRAINING_FRACTION: { type: 'number', min: 0, max: 1 },
  SCALP_HTF_VALIDATION_FRACTION: { type: 'number', min: 0, max: 1 },
  SCALP_HTF_MIN_TRAINING_TRADES: { type: 'number', min: 0 },
  SCALP_HTF_MIN_VALIDATION_TRADES: { type: 'number', min: 0 },
  SCALP_HTF_MIN_TRAINING_PF: { type: 'number' },
  SCALP_HTF_MIN_VALIDATION_PF: { type: 'number' },
  SCALP_HTF_MIN_TRAINING_RETURN: { type: 'number' },
  SCALP_HTF_MIN_VALIDATION_RETURN: { type: 'number' },
  SCALP_HTF_MAX_DRAWDOWN: { type: 'number' },
  SCALP_HTF_MIN_CONFIDENCE_LOWER: { type: 'number' },
  SCALP_HTF_MAX_POSITIONS: { type: 'number', min: 0 },
  SCALP_HTF_PORTFOLIO_POSITION_FRACTION: { type: 'number', min: 0, max: 1 },
  SCALP_HTF_MOMENTUM_REPORT_FILE: { type: 'string' },
  DAILY_MOMENTUM_MARKETS: { type: 'list' },
  DAILY_MOMENTUM_DAYS: { type: 'number', min: 0 },
  DAILY_MOMENTUM_SEGMENTS: { type: 'number' },
  DAILY_MOMENTUM_INITIAL_BALANCE: { type: 'number', min: 0 },
  DAILY_MOMENTUM_COST_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_POSITION_FRACTION: { type: 'number', min: 0, max: 1 },
  DAILY_MOMENTUM_MAX_POSITIONS: { type: 'number', min: 0 },
  DAILY_MOMENTUM_CANDLES_FILE: { type: 'string' },
  DAILY_MOMENTUM_REPORT_FILE: { type: 'string' },
  DAILY_MOMENTUM_ROBUSTNESS_REPORT_FILE: { type: 'string' },
  DAILY_MOMENTUM_ROBUSTNESS_SEGMENTS: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_SEGMENT_MODE: { type: 'string' },
  DAILY_MOMENTUM_ROBUSTNESS_MODES: { type: 'list' },
  DAILY_MOMENTUM_ROBUSTNESS_MAX_HOLD_DAYS: { type: 'int', min: 0 },
  DAILY_MOMENTUM_ROBUSTNESS_TREND_MIN_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_BREADTH_MIN: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_POSITION_FRACTION: { type: 'number', min: 0, max: 1 },
  DAILY_MOMENTUM_ROBUSTNESS_MAX_POSITIONS: { type: 'int', min: 0 },
  DAILY_MOMENTUM_ROBUSTNESS_COOLDOWN_AFTER_LOSS_DAYS: { type: 'int', min: 0 },
  DAILY_MOMENTUM_ROBUSTNESS_MAX_PORTFOLIO_DRAWDOWN_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_BENCHMARK_THRESHOLDS: { type: 'list' },
  DAILY_MOMENTUM_ROBUSTNESS_MIN_UP_BARS: { type: 'list' },
  DAILY_MOMENTUM_ROBUSTNESS_VOLATILITY_LOOKBACK_DAYS: { type: 'int', min: 0 },
  DAILY_MOMENTUM_ROBUSTNESS_VOLATILITY_TARGET_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_STOP_LOSS_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_MAX_ENTRY_GAP_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_ENTRY_EXECUTION: { type: 'enum', values: ['close', 'next_open'] },
  DAILY_MOMENTUM_ROBUSTNESS_EXIT_EXECUTION: { type: 'enum', values: ['close', 'next_open'] },
  DAILY_MOMENTUM_ROBUSTNESS_BENCHMARK_EXIT_CONFIRMATION_BARS: { type: 'int', min: 0 },
  DAILY_MOMENTUM_ROBUSTNESS_REGIME_EXIT_CONFIRMATION_BARS: { type: 'int', min: 0 },
  DAILY_MOMENTUM_ROBUSTNESS_RELATIVE_TREND_MIN_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_COST_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_MIN_RETURN_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_MAX_DRAWDOWN_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_MIN_WORST_SEGMENT_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_ROBUSTNESS_MIN_TRADES: { type: 'number', min: 0 },
  DAILY_MOMENTUM_ROLLING_CANDLES_FILE: { type: 'string' },
  DAILY_MOMENTUM_ROLLING_REPORT_FILE: { type: 'string' },
  DAILY_MOMENTUM_ROLLING_MARKETS: { type: 'list' },
  DAILY_MOMENTUM_ROLLING_WINDOWS: { type: 'list' },
  DAILY_MOMENTUM_ROLLING_MIN_TRADES: { type: 'number', min: 0 },
  DAILY_MOMENTUM_ROLLING_CONFIG_JSON: { type: 'string' },
  DAILY_MOMENTUM_ENTRY_EXECUTION: { type: 'enum', values: ['close', 'next_open'] },
  DAILY_MOMENTUM_EXIT_EXECUTION: { type: 'enum', values: ['close', 'next_open'] },
  DAILY_MOMENTUM_BENCHMARK_EXPOSURE_MIN_PERCENT: { type: 'number' },
  DAILY_MOMENTUM_BENCHMARK_EXPOSURE_MAX_PERCENT: { type: 'number' },
  DAILY_MARKET_NEUTRAL_CANDLES_FILE: { type: 'string' },
  DAILY_MARKET_NEUTRAL_REPORT_FILE: { type: 'string' },
  DAILY_MARKET_NEUTRAL_MARKETS: { type: 'list' },
  DAILY_MARKET_NEUTRAL_SEGMENTS: { type: 'number' },
  DAILY_MARKET_NEUTRAL_INITIAL_BALANCE: { type: 'number', min: 0 },
  DAILY_MARKET_NEUTRAL_LONG_EXPOSURE: { type: 'number' },
  DAILY_MARKET_NEUTRAL_SHORT_EXPOSURE: { type: 'number' },
  DAILY_MARKET_NEUTRAL_COST_PERCENT: { type: 'number' },
  DAILY_MARKET_NEUTRAL_SHORT_BORROW_COST_PER_DAY: { type: 'number' },
  MOMO_SHADOW_DIR: { type: 'string' },
  MOMO_SHADOW_MODE: { type: 'enum', values: ['fixed', 'regime'] },
  MOMO_SHADOW_MARKETS: { type: 'list' },
  MOMO_SHADOW_BENCHMARK_MARKET: { type: 'string' },
  MOMO_SHADOW_BENCHMARK_TREND_MIN_PERCENT: { type: 'number' },
  MOMO_SHADOW_EXIT_ON_BENCHMARK_OFF: { type: 'bool' },
  MOMO_SHADOW_INITIAL_BALANCE: { type: 'number', min: 0 },
  MOMO_SHADOW_COST_PERCENT: { type: 'number' },
  MOMO_SHADOW_TREND_MIN_PERCENT: { type: 'number' },
  MOMO_SHADOW_BREADTH_MIN: { type: 'number' },
  MOMO_SHADOW_POSITION_FRACTION: { type: 'number', min: 0, max: 1 },
  MOMO_SHADOW_MAX_POSITIONS: { type: 'number', min: 0 },
  MOMO_SHADOW_VOLATILITY_LOOKBACK_DAYS: { type: 'number', min: 0 },
  MOMO_SHADOW_VOLATILITY_TARGET_PERCENT: { type: 'number' },
  MOMO_SHADOW_ENTRY_EXECUTION: { type: 'enum', values: ['close', 'next_open'] },
  MOMO_SHADOW_FIXED_HOLD_DIR: { type: 'string' },
  MOMO_SHADOW_MAX_HOLD_HOURS: { type: 'number', min: 0 },
  MOMO_SHADOW_FIXED_HOLD_SPREAD_DIR: { type: 'string' },
  MOMO_SHADOW_MAX_SPREAD_PERCENT: { type: 'number' },
  MOMO_SHADOW_REQUEST_INTERVAL_MS: { type: 'number', min: 0 },
  MOMO_SHADOW_QUOTE_MARKETS: { type: 'list' },
  MOMO_SHADOW_QUOTE_SAMPLES: { type: 'number', min: 0 },
  MOMO_SHADOW_QUOTE_INTERVAL_MS: { type: 'number', min: 0 },
  MOMO_SHADOW_QUOTE_MAX_SPREAD_PERCENT: { type: 'number' },
  MOMO_SHADOW_QUOTE_REPORT_FILE: { type: 'string' },
  MOMO_SHADOW_QUOTE_HISTORY_FILE: { type: 'string' },
  MOMO_SHADOW_NEXT_OPEN_DIR: { type: 'string' },
  MOMO_SHADOW_STOP_LOSS_PERCENT: { type: 'number' },
  MOMO_SHADOW_TAKE_PROFIT_PERCENT: { type: 'number' },
  MOMO_SHADOW_NTFY_TOPIC: { type: 'string' },
  MOMO_SHADOW_COOLDOWN_AFTER_LOSS_DAYS: { type: 'number', min: 0 },
  MOMO_SHADOW_MAX_PORTFOLIO_DRAWDOWN_PERCENT: { type: 'number' },
  MOMO_SHADOW_MAX_ENTRY_GAP_PERCENT: { type: 'number' },
  MOMO_SHADOW_MAX_DAILY_CANDLE_AGE_HOURS: { type: 'number', min: 0 },
  MOMO_SHADOW_MIN_UP_BARS: { type: 'number', min: 0 },
  MOMO_SHADOW_POLL_MS: { type: 'number', min: 0 },
  MOMO_SHADOW_CANDIDATE_DIR: { type: 'string' },
  MOMO_SHADOW_VOLATILITY_DIR: { type: 'string' },
  MOMO_SHADOW_BENCHMARK_DIR: { type: 'string' },
  MOMO_SHADOW_FIXED_DIR: { type: 'string' },
  MOMO_SHADOW_REGIME_DIR: { type: 'string' },
  MOMO_SHADOW_OWNER_DIRS: { type: 'list' },
  MOMO_SHADOW_MIN_POLL_MS: { type: 'number', min: 0 },
  MOMO_SHADOW_REQUIRE_BENCHMARK_OPEN: { type: 'bool' },
  MOMO_SHADOW_ALLOW_START: { type: 'bool' },
  REGIME_CANDLES_FILE: { type: 'string' },
  REGIME_MARKETS: { type: 'list' },
  REGIME_SOURCE_UNIT_MINUTES: { type: 'number', min: 0 },
  REGIME_SIGNAL_UNIT_MINUTES: { type: 'number', min: 0 },
  REGIME_RSI_PERIOD: { type: 'number', min: 0 },
  REGIME_RSI_THRESHOLD: { type: 'number' },
  REGIME_TREND_LOOKBACK_HOURS: { type: 'number', min: 0 },
  REGIME_REQUIRE_UP_BAR: { type: 'bool' },
  REGIME_MAX_HOLD_HOURS: { type: 'number', min: 0 },
  REGIME_STOP_LOSS_PERCENT: { type: 'number' },
  REGIME_TAKE_PROFIT_PERCENT: { type: 'number' },
  REGIME_MAX_POSITIONS: { type: 'number', min: 0 },
  REGIME_POSITION_FRACTION: { type: 'number', min: 0, max: 1 },
  REGIME_INITIAL_BALANCE: { type: 'number', min: 0 },
  REGIME_COST_PERCENT: { type: 'number' },
  REGIME_TRAIN_FRACTION: { type: 'number', min: 0, max: 1 },
  REGIME_MAX_GAP_INTERVALS: { type: 'number', min: 0 },
  REGIME_REPORT_FILE: { type: 'string' },
  PAPER_AI_EVALUATION_MINUTES: { type: 'number', min: 0 },
  PAPER_AI_STOP_WAIT_MS: { type: 'number', min: 0 },
  PAPER_AI_MONITORING_FILE: { type: 'string' },
  // --- LEGACY / NON-SCALPING MODES ---
  CANDLE_UNIT: { type: 'int' },
  CANDLE_COUNT: { type: 'int', min: 0 },
  CHECK_INTERVAL: { type: 'int', min: 0 },
  ENABLE_DASHBOARD: { type: 'bool' },
  INVESTMENT_AMOUNT: { type: 'int', min: 0 },
  MIN_INVESTMENT_AMOUNT: { type: 'int', min: 0 },
  MAX_INVESTMENT_AMOUNT: { type: 'int', min: 0 },
  USE_PROPORTIONAL_INVESTMENT: { type: 'bool' },
  INITIAL_SEED_MONEY: { type: 'int', min: 0 },
  ALLOW_AVERAGING: { type: 'bool' },
  BUY_ONLY: { type: 'bool' },
  NEWS_CHECK_INTERVAL: { type: 'int', min: 0 },
  NEWS_SENTIMENT_THRESHOLD: { type: 'number' },
  EMA_SHORT: { type: 'int' },
  EMA_MID: { type: 'int' },
  MACD_FAST: { type: 'int' },
  MACD_SLOW: { type: 'int' },
  MACD_SIGNAL: { type: 'int' },
  TRAILING_STOP_PERCENT: { type: 'number' },
  VOLUME_PERIOD: { type: 'int', min: 0 },
  VOLUME_MULTIPLIER: { type: 'number' },
  CROSSOVER_RATE: { type: 'number' },
  MUTATION_RATE: { type: 'number' },
  ELITE_SIZE: { type: 'int', min: 0 },
  BACKTEST_CANDLE_UNIT: { type: 'int' },
  BACKTEST_CANDLE_COUNT: { type: 'int', min: 0 },
  // --- LOGGING ---
  LOG_LEVEL: { type: 'enum', values: ['error', 'warn', 'info', 'debug'] },
};

// Cross-key requirements evaluated after parsing. `when` receives the parsed
// values map; `reason` is printed verbatim on failure so the boot error states
// exactly which key is missing and why.
export const ENV_REQUIRED_RULES = [
  {
    keys: ['UPBIT_ACCESS_KEY', 'UPBIT_SECRET_KEY'],
    when: values => values.DRY_RUN === false,
    reason: 'DRY_RUN=false (실전투자)에서는 업비트 API 키가 필수입니다'
  }
];
