#!/usr/bin/env bash

set -euo pipefail

COINPILOT_SEALED_FORWARD_OUTPUT_DIR="${1:-.paper-forward-sealed-rsi-20260917-r2}"
COINPILOT_SEALED_FORWARD_STRICT_ONLY="${COINPILOT_SEALED_FORWARD_STRICT_ONLY:-false}"
case "$COINPILOT_SEALED_FORWARD_STRICT_ONLY" in
  true) COINPILOT_SEALED_FORWARD_DIAGNOSTIC_SHADOWS_ENABLED=false ;;
  false) COINPILOT_SEALED_FORWARD_DIAGNOSTIC_SHADOWS_ENABLED=true ;;
  *) echo "COINPILOT_SEALED_FORWARD_STRICT_ONLY must be true or false" >&2; exit 2 ;;
esac

exec env \
  PAPER_FORWARD_MODE=true \
  PAPER_FORWARD_VERBOSE=false \
  PAPER_SMOKE_OUTPUT_DIR="$COINPILOT_SEALED_FORWARD_OUTPUT_DIR" \
  PAPER_SMOKE_MARKETS='KRW-BTC,KRW-ETH,KRW-XRP,KRW-SOL' \
  PAPER_SMOKE_INTERVAL_MS=30000 \
  PAPER_SMOKE_SEED_MONEY=10000000 \
  SCALP_SIGNAL_PROFILE=rsi_rebound \
  SCALP_CANDLE_UNIT=1 \
  SCALP_CANDLE_COUNT=120 \
  SCALP_MAX_CANDLE_AGE_SECONDS=90 \
  SCALP_RSI_PERIOD=14 \
  SCALP_RSI_OVERSOLD=35 \
  SCALP_RSI_OVERBOUGHT=65 \
  SCALP_OVERSOLD_LOOKBACK=1 \
  SCALP_MIN_REBOUND_PERCENT=0.15 \
  SCALP_MIN_RSI_RECOVERY=2 \
  SCALP_MIN_VOLUME_RATIO=1 \
  SCALP_VOLUME_LOOKBACK=20 \
  SCALP_MIN_CLOSE_STRENGTH=0.65 \
  SCALP_TREND_PERIOD=30 \
  SCALP_TREND_SLOPE_LOOKBACK=3 \
  SCALP_MIN_TREND_SLOPE_PERCENT=-0.2 \
  SCALP_REQUIRE_PREVIOUS_HIGH_BREAK=true \
  SCALP_MAX_SIGNAL_RANGE_PERCENT=0 \
  SCALP_MIN_SIGNAL_RANGE_PERCENT=0 \
  SCALP_MAX_REBOUND_PERCENT=0 \
  SCALP_MARKET_REGIME_ENABLED=false \
  SCALP_MARKET_REGIME_LOOKBACK=5 \
  SCALP_MARKET_REGIME_MIN_BREADTH=0.5 \
  SCALP_MARKET_REGIME_MIN_RETURN_PERCENT=-0.2 \
  SCALP_REQUIRE_REBOUND_BELOW_OVERBOUGHT=false \
  SCALP_STOP_LOSS_PERCENT=1.2 \
  SCALP_TAKE_PROFIT_PERCENT=1.8 \
  SCALP_MAX_HOLD_MINUTES=30 \
  SCALP_MAX_LOSING_HOLD_MINUTES=0 \
  SCALP_COOLDOWN_AFTER_LOSS_MINUTES=15 \
  SCALP_MAX_CONSECUTIVE_LOSSES=3 \
  SCALP_LOSS_CIRCUIT_BREAKER_COUNT=0 \
  SCALP_LOSS_CIRCUIT_BREAKER_WINDOW_MINUTES=30 \
  SCALP_LOSS_CIRCUIT_BREAKER_COOLDOWN_MINUTES=60 \
  SCALP_ENTRY_DELAY_MIN_MS=1000 \
  SCALP_ENTRY_DELAY_MAX_MS=5000 \
  SCALP_MAX_ENTRY_RETRACE_PERCENT=0.25 \
  SCALP_MAX_ENTRY_CHASE_PERCENT=0.35 \
  SCALP_BREAK_EVEN_TRIGGER_PERCENT=0 \
  SCALP_BREAK_EVEN_OFFSET_PERCENT=0.05 \
  SCALP_TRAILING_ACTIVATION_PERCENT=0 \
  SCALP_TRAILING_STOP_PERCENT=0 \
  SCALP_WINNER_EXTEND_MINUTES=0 \
  SCALP_WINNER_EXTEND_MIN_PROFIT_PERCENT=0 \
  SCALP_WINNER_SHADOW_EXTEND_MINUTES=0 \
  SCALP_WINNER_SHADOW_EXTEND_MIN_PROFIT_PERCENT=0 \
  SCALP_WINNER_SHADOW_MAX_REBOUND_PERCENT=0 \
  SCALP_PAPER_DIAGNOSTIC_SHADOWS_ENABLED="$COINPILOT_SEALED_FORWARD_DIAGNOSTIC_SHADOWS_ENABLED" \
  SCALP_MAX_ENTRIES_PER_SIGNAL_WINDOW=0 \
  SCALP_RISK_CHECK_INTERVAL_MS=1000 \
  SCALP_MAX_RISK_DATA_GAP_SECONDS=30 \
  SCALP_MAX_ANALYSIS_DATA_GAP_SECONDS=60 \
  SCALP_PAPER_MIN_DAYS=7 \
  SCALP_PAPER_MIN_TRADES=20 \
  SCALP_PAPER_MIN_RETURN_PERCENT=0.2 \
  SCALP_PAPER_MAX_DRAWDOWN_PERCENT=15 \
  SCALP_PAPER_MAX_HEARTBEAT_GAP_MINUTES=15 \
  npm run paper:forward
